// lib/services/chat/chat_service.dart
import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:image_picker/image_picker.dart';
import '../../models/chat_message_model.dart';

class ChatService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;

  // Send Message
  Future<void> sendMessage({
    required String orderId,
    required String message,
    required String senderName,
    required String senderRole,
    String? imageUrl,
  }) async {
    final String currentUserId = _auth.currentUser!.uid;
    final DateTime now = DateTime.now();

    // 1. Add to Order_Chats collection
    final messageData = ChatMessageModel(
      id: '', // Generated by Firestore
      orderId: orderId,
      senderId: currentUserId,
      senderName: senderName,
      senderRole: senderRole,
      message: message,
      imageUrl: imageUrl,
      timestamp: now,
      isRead: false,
    ).toMap();

    await _firestore
        .collection('Order_Chats')
        .doc(orderId)
        .collection('messages')
        .add(messageData);

    // 2. Update Metadata in Order_Requests (For Order Card Preview)
    await _firestore.collection('Order_Requests').doc(orderId).update({
      'lastMessage': message,
      'lastMessageTime': Timestamp.fromDate(now),
      'lastMessageSender': currentUserId,
    });
  }

  // Send Image Message
  Future<void> sendImageMessage({
    required String orderId,
    required XFile image,
    required String senderName,
    required String senderRole,
  }) async {
    // Upload Image
    String fileName = 'chat_${DateTime.now().millisecondsSinceEpoch}.jpg';
    Reference ref = _storage.ref().child('chat_images/$orderId/$fileName');
    await ref.putFile(File(image.path));
    String imageUrl = await ref.getDownloadURL();

    await sendMessage(
      orderId: orderId,
      message: '📷 Image',
      senderName: senderName,
      senderRole: senderRole,
      imageUrl: imageUrl,
    );
  }

  // Get Messages Stream
  Stream<List<ChatMessageModel>> getMessages(String orderId) {
    return _firestore
        .collection('Order_Chats')
        .doc(orderId)
        .collection('messages')
        .orderBy('timestamp', descending: false)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => ChatMessageModel.fromMap(doc.data(), doc.id))
          .toList();
    });
  }

  // Mark Messages as Read
  Future<void> markMessagesAsRead(String orderId, String userId) async {
    // Implementation to mark opponent's messages as read
    // This is optional for now
  }
}